import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/Styles/globals.css'
import React from 'react'
import StyledComponentsRegistry from '@/Components/RegistryApp'
import ReduxProvider from '@/Components/ReduxProvider'
import MyModalProvider from '@/Components/MyModal'
import NextUIProvider from '@/Components/NextUIProvider'
import Web3Provider from '@/Components/Web3Provider'
import ClientREnder from '@/Components/ClientRender'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
          <StyledComponentsRegistry>
            <NextUIProvider>
              <ReduxProvider>
                <MyModalProvider>
                  {/* <ClientREnder>{children}</ClientREnder> */}
                  {children}
                </MyModalProvider>
              </ReduxProvider>
            </NextUIProvider>
          </StyledComponentsRegistry>
        </Web3Provider>
      </body>
    </html>
  )
}
